require(lme4)
require(coefplot2)
library(lmerTest)
library(pbkrtest)
library(multcomp)
library(contrast)

df_ef = read.csv('dpgmm_alpha15.37_bilateral_UW_EF__ALL_longdata.csv')
df_mem = read.csv('dpgmm_alpha15.37_bilateral_UW_MEM__ALL_longdata.csv')
df_adas = read.csv('dpgmm_alpha15.37_bilateral_ADAScog__ALL_longdata.csv')
df_avlt = read.csv('dpgmm_alpha15.37_bilateral_AVLT__ALL_longdata.csv')
df_hcicv = read.csv('dpgmm_alpha15.37_bilateral_FSX_HC_ICV__ALL_longdata.csv')
df_wmh = read.csv('dpgmm_alpha15.37_bilateral_WMH_percentOfICV__ALL_longdata.csv')
df_ef$RID = factor(df_ef$RID)
df_mem$RID = factor(df_mem$RID)
df_hcicv$RID = factor(df_hcicv$RID)
df_wmh$RID = factor(df_wmh$RID)
df_adas$RID = factor(df_adas$RID)
df_avlt$RID = factor(df_avlt$RID)
df_ef$group = factor(df_ef$group)
df_mem$group = factor(df_mem$group)
df_hcicv$group = factor(df_hcicv$group)
df_wmh$group = factor(df_wmh$group)
df_adas$group = factor(df_adas$group)
df_avlt$group = factor(df_avlt$group)

fm_uwef = lmer(UW_EF_ ~ group + group*UW_EF_postAV45_ + factor(diag_prior) + factor(diag_prior)*UW_EF_postAV45_ + factor(APOE4_BIN) + factor(APOE4_BIN)*UW_EF_postAV45_ + Age.AV45 + factor(Gender) + Edu..Yrs. + UW_EF_postAV45_ + (1 + UW_EF_postAV45_ | RID), df_ef)
fm_uwmem = lmer(UW_MEM_ ~ group + group*UW_MEM_postAV45_ + factor(diag_prior) + factor(diag_prior)*UW_MEM_postAV45_ + factor(APOE4_BIN) + factor(APOE4_BIN)*UW_MEM_postAV45_ + Age.AV45 + factor(Gender) + Edu..Yrs. + UW_MEM_postAV45_ + (1 + UW_MEM_postAV45_ | RID), df_mem)
fm_hcicv = lmer(FSX_HC.ICV_ ~ group + group*FSX_postAV45_ + factor(diag_prior) + factor(diag_prior)*FSX_postAV45_ + factor(APOE4_BIN) + factor(APOE4_BIN)*FSX_postAV45_ + Age.AV45 + factor(Gender) + Edu..Yrs. + FSX_postAV45_ + (1 + FSX_postAV45_ | RID), df_hcicv)
fm_wmh = lmer(WMH_percentOfICV. ~ group + group*WMH_postAV45. + factor(diag_prior) + factor(diag_prior)*WMH_postAV45. + factor(APOE4_BIN) + factor(APOE4_BIN)*WMH_postAV45. + Age.AV45 + factor(Gender) + Edu..Yrs. + WMH_postAV45. + (1 + WMH_postAV45. | RID), df_wmh)
fm_avlt = lmer(AVLT. ~ group + group*TIMEpostAV45_AVLT. + factor(diag_prior) + factor(diag_prior)*TIMEpostAV45_AVLT. + factor(APOE4_BIN) + factor(APOE4_BIN)*TIMEpostAV45_AVLT. + Age.AV45 + factor(Gender) + Edu..Yrs. + TIMEpostAV45_AVLT. + (1 + TIMEpostAV45_AVLT. | RID), df_avlt)
fm_adas = lmer(ADAScog. ~ group + group*TIMEpostAV45_ADAS. + factor(diag_prior) + factor(diag_prior)*TIMEpostAV45_ADAS. + factor(APOE4_BIN) + factor(APOE4_BIN)*TIMEpostAV45_ADAS. + Age.AV45 + factor(Gender) + Edu..Yrs. + TIMEpostAV45_ADAS. + (1 + TIMEpostAV45_ADAS. | RID), df_adas)

fm_uwef_cs = lmer(UW_EF_ ~ group + group*UW_EF_postAV45_ + factor(diag_prior) + factor(diag_prior)*UW_EF_postAV45_ + factor(APOE4_BIN) + factor(APOE4_BIN)*UW_EF_postAV45_ + CORTICAL_SUMMARY_prior + CORTICAL_SUMMARY_prior*UW_EF_postAV45_ + Age.AV45 + factor(Gender) + Edu..Yrs. + UW_EF_postAV45_ + (1 + UW_EF_postAV45_ | RID), df_ef)
fm_uwmem_cs = lmer(UW_MEM_ ~ group + group*UW_MEM_postAV45_ + factor(diag_prior) + factor(diag_prior)*UW_MEM_postAV45_ + factor(APOE4_BIN) + factor(APOE4_BIN)*UW_MEM_postAV45_ + CORTICAL_SUMMARY_prior + CORTICAL_SUMMARY_prior*UW_MEM_postAV45_ + Age.AV45 + factor(Gender) + Edu..Yrs. + UW_MEM_postAV45_ + (1 + UW_MEM_postAV45_ | RID), df_mem)
fm_hcicv_cs = lmer(FSX_HC.ICV_ ~ group + group*FSX_postAV45_ + factor(diag_prior) + factor(diag_prior)*FSX_postAV45_ + factor(APOE4_BIN) + factor(APOE4_BIN)*FSX_postAV45_ + CORTICAL_SUMMARY_prior + CORTICAL_SUMMARY_prior*FSX_postAV45_ + Age.AV45 + factor(Gender) + Edu..Yrs. + FSX_postAV45_ + (1 + FSX_postAV45_ | RID), df_hcicv)
fm_wmh_cs = lmer(WMH_percentOfICV. ~ group + group*WMH_postAV45. + factor(diag_prior) + factor(diag_prior)*WMH_postAV45. + factor(APOE4_BIN) + factor(APOE4_BIN)*WMH_postAV45. + CORTICAL_SUMMARY_prior + CORTICAL_SUMMARY_prior*WMH_postAV45. + Age.AV45 + factor(Gender) + Edu..Yrs. + WMH_postAV45. + (1 + WMH_postAV45. | RID), df_wmh)
fm_avlt_cs = lmer(AVLT. ~ group + group*TIMEpostAV45_AVLT. + factor(diag_prior) + factor(diag_prior)*TIMEpostAV45_AVLT. + factor(APOE4_BIN) + factor(APOE4_BIN)*TIMEpostAV45_AVLT. + CORTICAL_SUMMARY_prior + CORTICAL_SUMMARY_prior*TIMEpostAV45_AVLT. + Age.AV45 + factor(Gender) + Edu..Yrs. + TIMEpostAV45_AVLT. + (1 + TIMEpostAV45_AVLT. | RID), df_avlt)
fm_adas_cs = lmer(ADAScog. ~ group + group*TIMEpostAV45_ADAS. + factor(diag_prior) + factor(diag_prior)*TIMEpostAV45_ADAS. + factor(APOE4_BIN) + factor(APOE4_BIN)*TIMEpostAV45_ADAS. + CORTICAL_SUMMARY_prior + CORTICAL_SUMMARY_prior*TIMEpostAV45_ADAS. + Age.AV45 + factor(Gender) + Edu..Yrs. + TIMEpostAV45_ADAS. + (1 + TIMEpostAV45_ADAS. | RID), df_adas)


df_ef_n = read.csv('dpgmm_alpha15.37_bilateral_UW_EF__N_longdata.csv')
df_mem_n = read.csv('dpgmm_alpha15.37_bilateral_UW_MEM__N_longdata.csv')
df_adas_n = read.csv('dpgmm_alpha15.37_bilateral_ADAScog__N_longdata.csv')
df_avlt_n = read.csv('dpgmm_alpha15.37_bilateral_AVLT__N_longdata.csv')
df_hcicv_n = read.csv('dpgmm_alpha15.37_bilateral_FSX_HC_ICV__N_longdata.csv')
df_wmh_n = read.csv('dpgmm_alpha15.37_bilateral_WMH_percentOfICV__N_longdata.csv')
df_ef_n$RID = factor(df_ef_n$RID)
df_mem_n$RID = factor(df_mem_n$RID)
df_hcicv_n$RID = factor(df_hcicv_n$RID)
df_wmh_n$RID = factor(df_wmh_n$RID)
df_adas_n$RID = factor(df_adas_n$RID)
df_avlt_n$RID = factor(df_avlt_n$RID)
df_ef_n$group = factor(df_ef_n$group)
df_mem_n$group = factor(df_mem_n$group)
df_hcicv_n$group = factor(df_hcicv_n$group)
df_wmh_n$group = factor(df_wmh_n$group)
df_adas_n$group = factor(df_adas_n$group)
df_avlt_n$group = factor(df_avlt_n$group)

fm_uwef_n = lmer(UW_EF_ ~ group + group*UW_EF_postAV45_ + factor(APOE4_BIN) + factor(APOE4_BIN)*UW_EF_postAV45_ + Age.AV45 + factor(Gender) + Edu..Yrs. + UW_EF_postAV45_ + (1 + UW_EF_postAV45_ | RID), df_ef_n)
fm_uwmem_n = lmer(UW_MEM_ ~ group + group*UW_MEM_postAV45_ + factor(APOE4_BIN) + factor(APOE4_BIN)*UW_MEM_postAV45_ + Age.AV45 + factor(Gender) + Edu..Yrs. + UW_MEM_postAV45_ + (1 + UW_MEM_postAV45_ | RID), df_mem_n)
fm_hcicv_n = lmer(FSX_HC.ICV_ ~ group + group*FSX_postAV45_ + factor(APOE4_BIN) + factor(APOE4_BIN)*FSX_postAV45_ + Age.AV45 + factor(Gender) + Edu..Yrs. + FSX_postAV45_ + (1 + FSX_postAV45_ | RID), df_hcicv_n)
fm_wmh_n = lmer(WMH_percentOfICV. ~ group + group*WMH_postAV45. + factor(APOE4_BIN) + factor(APOE4_BIN)*WMH_postAV45. + Age.AV45 + factor(Gender) + Edu..Yrs. + WMH_postAV45. + (1 + WMH_postAV45. | RID), df_wmh_n)
fm_avlt_n = lmer(AVLT. ~ group + group*TIMEpostAV45_AVLT. + factor(APOE4_BIN) + factor(APOE4_BIN)*TIMEpostAV45_AVLT. + Age.AV45 + factor(Gender) + Edu..Yrs. + TIMEpostAV45_AVLT. + (1 + TIMEpostAV45_AVLT. | RID), df_avlt_n)
fm_adas_n = lmer(ADAScog. ~ group + group*TIMEpostAV45_ADAS. + factor(APOE4_BIN) + factor(APOE4_BIN)*TIMEpostAV45_ADAS. + Age.AV45 + factor(Gender) + Edu..Yrs. + TIMEpostAV45_ADAS. + (1 + TIMEpostAV45_ADAS. | RID), df_adas_n)

fm_uwef_n_cs = lmer(UW_EF_ ~ group + group*UW_EF_postAV45_ + factor(APOE4_BIN) + factor(APOE4_BIN)*UW_EF_postAV45_ + CORTICAL_SUMMARY_prior + CORTICAL_SUMMARY_prior*UW_EF_postAV45_ + Age.AV45 + factor(Gender) + Edu..Yrs. + UW_EF_postAV45_ + (1 + UW_EF_postAV45_ | RID), df_ef_n)
fm_uwmem_n_cs = lmer(UW_MEM_ ~ group + group*UW_MEM_postAV45_ + factor(APOE4_BIN) + factor(APOE4_BIN)*UW_MEM_postAV45_ + CORTICAL_SUMMARY_prior + CORTICAL_SUMMARY_prior*UW_MEM_postAV45_ + Age.AV45 + factor(Gender) + Edu..Yrs. + UW_MEM_postAV45_ + (1 + UW_MEM_postAV45_ | RID), df_mem_n)
fm_hcicv_n_cs = lmer(FSX_HC.ICV_ ~ group + group*FSX_postAV45_ + factor(APOE4_BIN) + factor(APOE4_BIN)*FSX_postAV45_ + CORTICAL_SUMMARY_prior + CORTICAL_SUMMARY_prior*FSX_postAV45_ + Age.AV45 + factor(Gender) + Edu..Yrs. + FSX_postAV45_ + (1 + FSX_postAV45_ | RID), df_hcicv_n)
fm_wmh_n_cs = lmer(WMH_percentOfICV. ~ group + group*WMH_postAV45. + factor(APOE4_BIN) + factor(APOE4_BIN)*WMH_postAV45. + CORTICAL_SUMMARY_prior + CORTICAL_SUMMARY_prior*WMH_postAV45. + Age.AV45 + factor(Gender) + Edu..Yrs. + WMH_postAV45. + (1 + WMH_postAV45. | RID), df_wmh_n)
fm_avlt_n_cs = lmer(AVLT. ~ group + group*TIMEpostAV45_AVLT. + factor(APOE4_BIN) + factor(APOE4_BIN)*TIMEpostAV45_AVLT. + CORTICAL_SUMMARY_prior + CORTICAL_SUMMARY_prior*TIMEpostAV45_AVLT. + Age.AV45 + factor(Gender) + Edu..Yrs. + TIMEpostAV45_AVLT. + (1 + TIMEpostAV45_AVLT. | RID), df_avlt_n)
fm_adas_n_cs = lmer(ADAScog. ~ group + group*TIMEpostAV45_ADAS. + factor(APOE4_BIN) + factor(APOE4_BIN)*TIMEpostAV45_ADAS. + CORTICAL_SUMMARY_prior + CORTICAL_SUMMARY_prior*TIMEpostAV45_ADAS. + Age.AV45 + factor(Gender) + Edu..Yrs. + TIMEpostAV45_ADAS. + (1 + TIMEpostAV45_ADAS. | RID), df_adas_n)

uwef_anova = as.matrix(anova(fm_uwef))
uwmem_anova = as.matrix(anova(fm_uwmem))
wmh_anova = as.matrix(anova(fm_wmh))
adas_anova = as.matrix(anova(fm_adas))
avlt_anova = as.matrix(anova(fm_avlt))

uwef_cs_anova = as.matrix(anova(fm_uwef_cs))
uwmem_cs_anova = as.matrix(anova(fm_uwmem_cs))
wmh_cs_anova = as.matrix(anova(fm_wmh_cs))
adas_cs_anova = as.matrix(anova(fm_adas_cs))
avlt_cs_anova = as.matrix(anova(fm_avlt_cs))

uwef_n_anova = as.matrix(anova(fm_uwef_n))
uwmem_n_anova = as.matrix(anova(fm_uwmem_n))
wmh_n_anova = as.matrix(anova(fm_wmh_n))
adas_n_anova = as.matrix(anova(fm_adas_n))
avlt_n_anova = as.matrix(anova(fm_avlt_n))

uwef_n_cs_anova = as.matrix(anova(fm_uwef_n_cs))
uwmem_n_cs_anova = as.matrix(anova(fm_uwmem_n_cs))
wmh_n_cs_anova = as.matrix(anova(fm_wmh_n_cs))
adas_n_cs_anova = as.matrix(anova(fm_adas_n_cs))
avlt_n_cs_anova = as.matrix(anova(fm_avlt_n_cs))

write.csv(uwef_anova, file = "uwef_all_anova.csv", na = "")
write.csv(uwmem_anova, file = "uwmem_all_anova.csv", na = "")
write.csv(wmh_anova, file = "wmh_all_anova.csv", na = "")
write.csv(adas_anova, file = "adas_all_anova.csv", na = "")
write.csv(avlt_anova, file = "avlt_all_anova.csv", na = "")
write.csv(uwef_cs_anova, file = "uwef_all_cs_anova.csv", na = "")
write.csv(uwmem_cs_anova, file = "uwmem_all_cs_anova.csv", na = "")
write.csv(wmh_cs_anova, file = "wmh_all_cs_anova.csv", na = "")
write.csv(adas_cs_anova, file = "adas_all_cs_anova.csv", na = "")
write.csv(avlt_cs_anova, file = "avlt_all_cs_anova.csv", na = "")

write.csv(uwef_n_anova, file = "uwef_n_anova.csv", na = "")
write.csv(uwmem_n_anova, file = "uwmem_n_anova.csv", na = "")
write.csv(wmh_n_anova, file = "wmh_n_anova.csv", na = "")
write.csv(adas_n_anova, file = "adas_n_anova.csv", na = "")
write.csv(avlt_n_anova, file = "avlt_n_anova.csv", na = "")
write.csv(uwef_n_cs_anova, file = "uwef_n_cs_anova.csv", na = "")
write.csv(uwmem_n_cs_anova, file = "uwmem_n_cs_anova.csv", na = "")
write.csv(wmh_n_cs_anova, file = "wmh_n_cs_anova.csv", na = "")
write.csv(adas_n_cs_anova, file = "adas_n_cs_anova.csv", na = "")
write.csv(avlt_n_cs_anova, file = "avlt_n_cs_anova.csv", na = "")


contrasts_n = read.csv('contrasts_n.csv')

test = glht(fm_wmh_n,linfct=data.matrix(contrasts_n))
test2 = glht(fm_wmh_n,linfct=mcp(group='Tukey'))
summary(test)
summary(test2)