from utils import *

lut_file = "../FreeSurferColorLUT.txt"
groups_included = {}

clusters = [('ctx-lh-caudalmiddlefrontal', [1003]),
            ('ctx-lh-lateralorbitofrontal', [1012]),
            ('ctx-lh-medialorbitofrontal', [1014]),
            ('ctx-lh-parsopercularis', [1018]),
            ('ctx-lh-parsorbitalis', [1019]),
            ('ctx-lh-parstriangularis', [1020]),
            ('ctx-lh-rostralmiddlefrontal', [1027]),
            ('ctx-lh-superiorfrontal', [1028]),
            ('ctx-lh-frontalpole', [1032]), 
            ('ctx-rh-caudalmiddlefrontal', [2003]), 
            ('ctx-rh-lateralorbitofrontal', [2012]), 
            ('ctx-rh-medialorbitofrontal', [2014]), 
            ('ctx-rh-parsopercularis', [2018]), 
            ('ctx-rh-parsorbitalis', [2019]), 
            ('ctx-rh-parstriangularis', [2020]), 
            ('ctx-rh-rostralmiddlefrontal', [2027]), 
            ('ctx-rh-superiorfrontal', [2028]), 
            ('ctx-rh-frontalpole', [2032]), 
            ('ctx-lh-caudalanteriorcingulate', [1002]), 
            ('ctx-lh-isthmuscingulate', [1010]), 
            ('ctx-lh-posteriorcingulate', [1023]), 
            ('ctx-lh-rostralanteriorcingulate', [1026]), 
            ('ctx-rh-caudalanteriorcingulate', [2002]), 
            ('ctx-rh-isthmuscingulate', [2010]), 
            ('ctx-rh-posteriorcingulate', [2023]), 
            ('ctx-rh-rostralanteriorcingulate', [2026]), 
            ('ctx-lh-inferiorparietal', [1008]), 
            ('ctx-lh-precuneus', [1025]), 
            ('ctx-lh-superiorparietal', [1029]), 
            ('ctx-lh-supramarginal', [1031]), 
            ('ctx-rh-inferiorparietal', [2008]), 
            ('ctx-rh-precuneus', [2025]), 
            ('ctx-rh-superiorparietal', [2029]), 
            ('ctx-rh-supramarginal', [2031]), 
            ('ctx-lh-middletemporal', [1015]), 
            ('ctx-lh-superiortemporal', [1030]),
            ('ctx-rh-middletemporal', [2015]),
            ('ctx-rh-superiortemporal', [2030]),
            ('left_basal_ganglia', [11,12,13]),
            ('right_basal_ganglia', [50,51,52]),
            ('left_occipital', [1011,1005,1013,1021]),
            ('right_occipital', [2011,2005,2013,2021]),
            ('left_central_gyri', [1017,1024,1022]),
            ('right_central_gyri', [2017,2024,2022]),
            ('left_thalamus', [10]),
            ('right_thalamus', [49]),
            ('left_cerebGM', [8]),
            ('right_cerebGM', [47]),
            ('left_cerebWM', [7]),
            ('right_cerebWM', [46]),
            ('brainstem', [16]),
            ('hemiWM', [2,41,77,251,252,253,254,255,1004,2004]),
            ('non_hemiWM', [85]),
            ('left_hippocampus', [17,1006,1009,1016,1033,1034]),
            ('right_hippocampus', [53,2006,2009,2016,2033,2034]),
            ('other', [2000,1000,60,1035,2007,80,2001,18,2035,62,54,1001,58,1007,28,26,30])]
print "\n\nGROUPING AGG"
filepath = "aggregions.mat"
all_groups = [b for a,b in clusters]
names = [a for a,b in clusters]
groups_included[filepath] = [i for g in all_groups for i in g]
createROIGrouping(names, all_groups, filepath)
printROIGrouping(names, all_groups, lut_file)
# create input for fake aparc so we can visualize grouping
out_file = '../output/fake_aparc_inputs/GROUP_AGG.mat'
sio.savemat(out_file, {'regions': [{'inds': v, 'val': i} for i,v in enumerate(all_groups)]})
print groups_included

clusters = [('ctx-lh-caudalmiddlefrontal', [1003]),
            ('ctx-lh-lateralorbitofrontal', [1012]),
            ('ctx-lh-medialorbitofrontal', [1014]),
            ('ctx-lh-parsopercularis', [1018]),
            ('ctx-lh-parsorbitalis', [1019]),
            ('ctx-lh-parstriangularis', [1020]),
            ('ctx-lh-rostralmiddlefrontal', [1027]),
            ('ctx-lh-superiorfrontal', [1028]),
            ('ctx-lh-frontalpole', [1032]),
            ('ctx-rh-caudalmiddlefrontal', [2003]),
            ('ctx-rh-lateralorbitofrontal', [2012]),
            ('ctx-rh-medialorbitofrontal', [2014]),
            ('ctx-rh-parsopercularis', [2018]),
            ('ctx-rh-parsorbitalis', [2019]),
            ('ctx-rh-parstriangularis', [2020]),
            ('ctx-rh-rostralmiddlefrontal', [2027]),
            ('ctx-rh-superiorfrontal', [2028]),
            ('ctx-rh-frontalpole', [2032]),
            ('ctx-lh-caudalanteriorcingulate', [1002]),
            ('ctx-lh-isthmuscingulate', [1010]),
            ('ctx-lh-posteriorcingulate', [1023]),
            ('ctx-lh-rostralanteriorcingulate', [1026]),
            ('ctx-rh-caudalanteriorcingulate', [2002]),
            ('ctx-rh-isthmuscingulate', [2010]),
            ('ctx-rh-posteriorcingulate', [2023]),
            ('ctx-rh-rostralanteriorcingulate', [2026]),
            ('ctx-lh-inferiorparietal', [1008]),
            ('ctx-lh-precuneus', [1025]),
            ('ctx-lh-superiorparietal', [1029]),
            ('ctx-lh-supramarginal', [1031]),
            ('ctx-rh-inferiorparietal', [2008]),
            ('ctx-rh-precuneus', [2025]),
            ('ctx-rh-superiorparietal', [2029]),
            ('ctx-rh-supramarginal', [2031]),
            ('ctx-lh-middletemporal', [1015]),
            ('ctx-lh-superiortemporal', [1030]),
            ('ctx-rh-middletemporal', [2015]),
            ('ctx-rh-superiortemporal', [2030]),
            ('Left-Caudate', [11]),
            ('Left-Putamen', [12]),
            ('Left-Pallidum', [13]),
            ('Right-Caudate', [50]),
            ('Right-Putamen', [51]),
            ('Right-Pallidum', [52]),
            ('ctx-lh-lateraloccipital', [1011]),
            ('ctx-lh-cuneus', [1005]),
            ('ctx-lh-lingual', [1013]),
            ('ctx-lh-pericalcarine', [1021]),
            ('ctx-rh-lateraloccipital', [2011]),
            ('ctx-rh-cuneus', [2005]),
            ('ctx-rh-lingual', [2013]),
            ('ctx-rh-pericalcarine', [2021]),
            ('ctx-lh-paracentral', [1017]),
            ('ctx-lh-precentral', [1024]),
            ('ctx-lh-postcentral', [1022]),
            ('ctx-rh-paracentral', [2017]),
            ('ctx-rh-precentral', [2024]),
            ('ctx-rh-postcentral', [2022]),
            ('Left-Thalamus-Proper', [10]),
            ('Right-Thalamus-Proper', [49]),
            ('Left-Cerebellum-Cortex', [8]),
            ('Right-Cerebellum-Cortex', [47]),
            ('Left-Cerebellum-White-Matter', [7]),
            ('Right-Cerebellum-White-Matter', [46]),
            ('Brain-Stem', [16]),
            ('Left-Cerebral-White-Matter', [2]),
            ('Right-Cerebral-White-Matter', [41]),
            ('WM-hypointensities', [77]),
            ('CC_Posterior', [251]),
            ('CC_Mid_Posterior', [252]),
            ('CC_Central', [253]),
            ('CC_Mid_Anterior', [254]),
            ('CC_Anterior', [255]),
            ('ctx-lh-corpuscallosum', [1004]),
            ('ctx-rh-corpuscallosum', [2004]),
            ('Optic-Chiasm', [85]),
            ('Left-Hippocampus', [17]),
            ('ctx-lh-entorhinal', [1006]),
            ('ctx-lh-inferiortemporal', [1009]),
            ('ctx-lh-parahippocampal', [1016]),
            ('ctx-lh-temporalpole', [1033]),
            ('ctx-lh-transversetemporal', [1034]),
            ('Right-Hippocampus', [53]),
            ('ctx-rh-entorhinal', [2006]),
            ('ctx-rh-inferiortemporal', [2009]),
            ('ctx-rh-parahippocampal', [2016]),
            ('ctx-rh-temporalpole', [2033]),
            ('ctx-rh-transversetemporal', [2034]),
            ('ctx-rh-unknown', [2000]),
            ('ctx-lh-unknown', [1000]),
            ('Right-VentralDC', [60]),
            ('ctx-lh-insula', [1035]),
            ('ctx-rh-fusiform', [2007]),
            ('non-WM-hypointensities', [80]),
            ('ctx-rh-bankssts', [2001]),
            ('Left-Amygdala', [18]),
            ('ctx-rh-insula', [2035]),
            ('Right-vessel', [62]),
            ('Right-Amygdala', [54]),
            ('ctx-lh-bankssts', [1001]),
            ('Right-Accumbens-area', [58]),
            ('ctx-lh-fusiform', [1007]),
            ('Left-VentralDC', [28]),
            ('Left-Accumbens-area', [26]), 
            ('Left-vessel', [30])]
print "\n\nGROUPING ALLREGIONS"
filepath = "allregions.mat"
all_groups = [b for a,b in clusters]
names = [a for a,b in clusters]
groups_included[filepath] = [i for g in all_groups for i in g]
createROIGrouping(names, all_groups, filepath)
printROIGrouping(names, all_groups, lut_file)
# create input for fake aparc so we can visualize grouping
out_file = '../output/fake_aparc_inputs/GROUP_ALLREGIONS.mat'
sio.savemat(out_file, {'regions': [{'inds': v, 'val': i} for i,v in enumerate(all_groups)]})
print groups_included

clusters = [('L_entorhinal',[1006]),
            ('R_entorhinal',[2006]),
            ('L_hippocampus',[17]),
            ('R_hippocampus',[53]),
            ('L_parahippocampal',[1016]),
            ('L_fusiform',[1007]),
            ('L_lingual',[1013]),
            ('L_amygdala',[18]),
            ('R_parahippocampal',[2016]),
            ('R_fusiform',[2007]),
            ('R_lingual',[2013]),
            ('R_amygdala',[54]),
            ('L_middletemporal',[1015]),
            ('L_thalamus',[10]),
            ('L_caudantcing',[1002]),
            ('L_rostantcing',[1026]),
            ('L_postcing',[1023]),
            ('L_isthmuscing',[1010]),
            ('L_insula',[1035]),
            ('L_inferiortemporal',[1009]),
            ('L_temppole',[1033]),
            ('R_middletemporal',[2015]),
            ('R_thalamus',[49]),
            ('R_caudantcing',[2002]),
            ('R_rostantcing',[2026]),
            ('R_postcing',[2023]),
            ('R_isthmuscing',[2010]),
            ('R_insula',[2035]),
            ('R_inferiortemporal',[2009]),
            ('R_temppole',[2033]),
            ('L_frontalassociationctx_SUPFR',[1028]),
            ('L_frontalassociationctx_FPORB',[1012,1014,1032]),
            ('L_frontalassociationctx_MIDFR',[1003,1027]),
            ('L_frontalassociationctx_PARSFR',[1018,1019,1020]),
            ('L_caudate',[11]),
            ('L_putamen',[12]),
            ('L_lateraloccipital',[1011]),
            ('L_parietalsupramarginal',[1031]),
            ('L_parietalinferior',[1008]),
            ('L_superiortemporal',[1030]),
            ('L_pallidum',[13]),
            ('L_parietalsuperior',[1029]),
            ('L_precuneus',[1025]),
            ('L_bankSTS',[1001]),
            ('L_accumbens',[26]),
            ('L_tranvtemp',[1034]),
            ('R_frontalassociationctx_SUPFR',[2028]),
            ('R_frontalassociationctx_FPORB',[2012,2014,2032]),
            ('R_frontalassociationctx_MIDFR',[2003,2027]),
            ('R_frontalassociationctx_PARSFR',[2018,2019,2020]),
            ('R_caudate',[50]),
            ('R_putamen',[51]),
            ('R_lateraloccipital',[2011]),
            ('R_parietalsupramarginal',[2031]),
            ('R_parietalinferior',[2008]),
            ('R_superiortemporal',[2030]),
            ('R_pallidum',[52]),
            ('R_parietalsuperior',[2029]),
            ('R_precuneus',[2025]),
            ('R_bankSTS',[2001]),
            ('R_accumbens',[58]),
            ('R_tranvtemp',[2034]),
            ('L_pericalcarine',[1021]),
            ('L_postcentral',[1022]),
            ('L_cuneus',[1005]),
            ('L_precentral',[1024]),
            ('L_paracentral',[1017]),
            ('R_pericalcarine',[2021]),
            ('R_postcentral',[2022]),
            ('R_cuneus',[2005]),
            ('R_precentral',[2024]),
            ('R_paracentral',[2017]),
            ('A_hemiw',[2,41,251,252,253,254,255]),
            ('A_cereg',[8,47]),
            ('A_cerew',[7,46]),
            ('brainstem',[16]),
            ('other',[5,14,15,24,28,30,44,60,62,72,77,80,85,1000,1004,2000,2004]),
            ('choroid',[31,63])]
print "\n\nGROUPING TAU"
filepath = "tauregions.mat"
all_groups = [b for a,b in clusters]
names = [a for a,b in clusters]
groups_included[filepath] = [i for g in all_groups for i in g]
createROIGrouping(names, all_groups, filepath)
printROIGrouping(names, all_groups, lut_file)
# create input for fake aparc so we can visualize grouping
out_file = '../output/fake_aparc_inputs/GROUP_TAU.mat'
sio.savemat(out_file, {'regions': [{'inds': v, 'val': i} for i,v in enumerate(all_groups)]})
print groups_included


clusters = [('ctx-lh-caudalmiddlefrontal', [1003]),
            ('ctx-lh-lateralorbitofrontal', [1012]),
            ('ctx-lh-medialorbitofrontal', [1014]),
            ('ctx-lh-parsopercularis', [1018]),
            ('ctx-lh-parsorbitalis', [1019]),
            ('ctx-lh-parstriangularis', [1020]),
            ('ctx-lh-rostralmiddlefrontal', [1027]),
            ('ctx-lh-superiorfrontal', [1028]),
            ('ctx-lh-frontalpole', [1032]),
            ('ctx-rh-caudalmiddlefrontal', [2003]),
            ('ctx-rh-lateralorbitofrontal', [2012]),
            ('ctx-rh-medialorbitofrontal', [2014]),
            ('ctx-rh-parsopercularis', [2018]),
            ('ctx-rh-parsorbitalis', [2019]),
            ('ctx-rh-parstriangularis', [2020]),
            ('ctx-rh-rostralmiddlefrontal', [2027]),
            ('ctx-rh-superiorfrontal', [2028]),
            ('ctx-rh-frontalpole', [2032]),
            ('ctx-lh-caudalanteriorcingulate', [1002]),
            ('ctx-lh-isthmuscingulate', [1010]),
            ('ctx-lh-posteriorcingulate', [1023]),
            ('ctx-lh-rostralanteriorcingulate', [1026]),
            ('ctx-rh-caudalanteriorcingulate', [2002]),
            ('ctx-rh-isthmuscingulate', [2010]),
            ('ctx-rh-posteriorcingulate', [2023]),
            ('ctx-rh-rostralanteriorcingulate', [2026]),
            ('ctx-lh-inferiorparietal', [1008]),
            ('ctx-lh-precuneus', [1025]),
            ('ctx-lh-superiorparietal', [1029]),
            ('ctx-lh-supramarginal', [1031]),
            ('ctx-rh-inferiorparietal', [2008]),
            ('ctx-rh-precuneus', [2025]),
            ('ctx-rh-superiorparietal', [2029]),
            ('ctx-rh-supramarginal', [2031]),
            ('ctx-lh-middletemporal', [1015]),
            ('ctx-lh-superiortemporal', [1030]),
            ('ctx-rh-middletemporal', [2015]),
            ('ctx-rh-superiortemporal', [2030]),
            ('Left-Caudate', [11]),
            ('Left-Putamen', [12]),
            ('Left-Pallidum', [13]),
            ('Right-Caudate', [50]),
            ('Right-Putamen', [51]),
            ('Right-Pallidum', [52]),
            ('ctx-lh-lateraloccipital', [1011]),
            ('ctx-lh-cuneus', [1005]),
            ('ctx-lh-lingual', [1013]),
            ('ctx-lh-pericalcarine', [1021]),
            ('ctx-rh-lateraloccipital', [2011]),
            ('ctx-rh-cuneus', [2005]),
            ('ctx-rh-lingual', [2013]),
            ('ctx-rh-pericalcarine', [2021]),
            ('ctx-lh-paracentral', [1017]),
            ('ctx-lh-precentral', [1024]),
            ('ctx-lh-postcentral', [1022]),
            ('ctx-rh-paracentral', [2017]),
            ('ctx-rh-precentral', [2024]),
            ('ctx-rh-postcentral', [2022]),
            ('Left-Thalamus-Proper', [10]),
            ('Right-Thalamus-Proper', [49]),
            ('Left-Cerebellum-Cortex', [8]),
            ('Right-Cerebellum-Cortex', [47]),
            ('Left-Cerebellum-White-Matter', [7]),
            ('Right-Cerebellum-White-Matter', [46]),
            ('Brain-Stem', [16]),
            ('Left-Cerebral-White-Matter', [2]),
            ('Right-Cerebral-White-Matter', [41]),
            ('CC', [251,252,253,254,255]),
            ('Left-Hippocampus', [17]),
            ('ctx-lh-entorhinal', [1006]),
            ('ctx-lh-inferiortemporal', [1009]),
            ('ctx-lh-parahippocampal', [1016]),
            ('ctx-lh-temporalpole', [1033]),
            ('ctx-lh-transversetemporal', [1034]),
            ('Right-Hippocampus', [53]),
            ('ctx-rh-entorhinal', [2006]),
            ('ctx-rh-inferiortemporal', [2009]),
            ('ctx-rh-parahippocampal', [2016]),
            ('ctx-rh-temporalpole', [2033]),
            ('ctx-rh-transversetemporal', [2034]),
            ('ctx-lh-insula', [1035]),
            ('ctx-rh-fusiform', [2007]),
            ('ctx-rh-bankssts', [2001]),
            ('Left-Amygdala', [18]),
            ('ctx-rh-insula', [2035]),
            ('Right-Amygdala', [54]),
            ('ctx-lh-bankssts', [1001]),
            ('Right-Accumbens-area', [58]),
            ('ctx-lh-fusiform', [1007]),
            ('Left-Accumbens-area', [26]), 
            ('Other', [30,62,1004,2004,1000,2000,85,80,77,60,28])]
print "\n\nGROUPING MOSTREGIONS"
filepath = "mostregions.mat"
all_groups = [b for a,b in clusters]
names = [a for a,b in clusters]
groups_included[filepath] = [i for g in all_groups for i in g]
createROIGrouping(names, all_groups, filepath)
printROIGrouping(names, all_groups, lut_file)
# create input for fake aparc so we can visualize grouping
out_file = '../output/fake_aparc_inputs/GROUP_MOSTREGIONS.mat'
sio.savemat(out_file, {'regions': [{'inds': v, 'val': i} for i,v in enumerate(all_groups)]})
print groups_included