
input_file = '/usr/local/jagust/ADNI_BL_AV45Neg_Normals.csv'
df = read.csv(input_file)
slope.thresh = 0.004

# get the accumulators
# df = df[complete.cases(df$AV45_NONTP_BigRef_Slope),]
# df$accum = factor(df$AV45_NONTP_BigRef_Slope > slope.thresh)
df = df[complete.cases(df$AV45_NONTP_BigRef_Slope_3pts),]
df$accum = factor(df$AV45_NONTP_BigRef_Slope_3pts > slope.thresh)

# output file name
# out.name = '/usr/local/jagust/AV45_NegNormal_accumAllgroup_region_anova.csv'
out.name = '/usr/local/jagust/AV45_NegNormal_accum3ptgroup_region_anova.csv'

demog = c('RID','Gender','accum','APOE4_BIN','Age.AV45','AV45_NONTP_BigRef_Slope','AV45_NONTP_BigRef_Slope_3pts')
# regions = c('CTX_LH_BANKSSTS','CTX_LH_CAUDALANTERIORCINGULATE','CTX_LH_CAUDALMIDDLEFRONTAL','CTX_LH_CUNEUS','CTX_LH_ENTORHINAL','CTX_LH_FRONTALPOLE','CTX_LH_FUSIFORM','CTX_LH_INFERIORPARIETAL','CTX_LH_INFERIORTEMPORAL','CTX_LH_INSULA','CTX_LH_ISTHMUSCINGULATE','CTX_LH_LATERALOCCIPITAL','CTX_LH_LATERALORBITOFRONTAL','CTX_LH_LINGUAL','CTX_LH_MEDIALORBITOFRONTAL','CTX_LH_MIDDLETEMPORAL','CTX_LH_PARACENTRAL','CTX_LH_PARAHIPPOCAMPAL','CTX_LH_PARSOPERCULARIS','CTX_LH_PARSORBITALIS','CTX_LH_PARSTRIANGULARIS','CTX_LH_PERICALCARINE','CTX_LH_POSTCENTRAL','CTX_LH_POSTERIORCINGULATE','CTX_LH_PRECENTRAL','CTX_LH_PRECUNEUS','CTX_LH_ROSTRALANTERIORCINGULATE','CTX_LH_ROSTRALMIDDLEFRONTAL','CTX_LH_SUPERIORFRONTAL','CTX_LH_SUPERIORPARIETAL','CTX_LH_SUPERIORTEMPORAL','CTX_LH_SUPRAMARGINAL','CTX_LH_TEMPORALPOLE','CTX_LH_TRANSVERSETEMPORAL','CTX_RH_BANKSSTS','CTX_RH_CAUDALANTERIORCINGULATE','CTX_RH_CAUDALMIDDLEFRONTAL','CTX_RH_CUNEUS','CTX_RH_ENTORHINAL','CTX_RH_FRONTALPOLE','CTX_RH_FUSIFORM','CTX_RH_INFERIORPARIETAL','CTX_RH_INFERIORTEMPORAL','CTX_RH_INSULA','CTX_RH_ISTHMUSCINGULATE','CTX_RH_LATERALOCCIPITAL','CTX_RH_LATERALORBITOFRONTAL','CTX_RH_LINGUAL','CTX_RH_MEDIALORBITOFRONTAL','CTX_RH_MIDDLETEMPORAL','CTX_RH_PARACENTRAL','CTX_RH_PARAHIPPOCAMPAL','CTX_RH_PARSOPERCULARIS','CTX_RH_PARSORBITALIS','CTX_RH_PARSTRIANGULARIS','CTX_RH_PERICALCARINE','CTX_RH_POSTCENTRAL','CTX_RH_POSTERIORCINGULATE','CTX_RH_PRECENTRAL','CTX_RH_PRECUNEUS','CTX_RH_ROSTRALANTERIORCINGULATE','CTX_RH_ROSTRALMIDDLEFRONTAL','CTX_RH_SUPERIORFRONTAL','CTX_RH_SUPERIORPARIETAL','CTX_RH_SUPERIORTEMPORAL','CTX_RH_SUPRAMARGINAL','CTX_RH_TEMPORALPOLE','CTX_RH_TRANSVERSETEMPORAL','LEFT_ACCUMBENS_AREA','LEFT_AMYGDALA','LEFT_CAUDATE','LEFT_CHOROID_PLEXUS','LEFT_HIPPOCAMPUS','LEFT_PALLIDUM','LEFT_PUTAMEN','LEFT_THALAMUS_PROPER','LEFT_VENTRALDC','RIGHT_ACCUMBENS_AREA','RIGHT_AMYGDALA','RIGHT_CAUDATE','RIGHT_CHOROID_PLEXUS','RIGHT_HIPPOCAMPUS','RIGHT_PALLIDUM','RIGHT_PUTAMEN','RIGHT_THALAMUS_PROPER','RIGHT_VENTRALDC')
regions = c('CTX_LH_CAUDALMIDDLEFRONTAL', 'CTX_LH_LATERALORBITOFRONTAL', 'CTX_LH_MEDIALORBITOFRONTAL', 'CTX_LH_PARSOPERCULARIS', 'CTX_LH_PARSORBITALIS', 'CTX_LH_PARSTRIANGULARIS', 'CTX_LH_ROSTRALMIDDLEFRONTAL', 'CTX_LH_SUPERIORFRONTAL', 'CTX_LH_FRONTALPOLE', 'CTX_RH_CAUDALMIDDLEFRONTAL', 'CTX_RH_LATERALORBITOFRONTAL', 'CTX_RH_MEDIALORBITOFRONTAL', 'CTX_RH_PARSOPERCULARIS', 'CTX_RH_PARSORBITALIS', 'CTX_RH_PARSTRIANGULARIS', 'CTX_RH_ROSTRALMIDDLEFRONTAL', 'CTX_RH_SUPERIORFRONTAL', 'CTX_RH_FRONTALPOLE', 'CTX_LH_INFERIORPARIETAL', 'CTX_LH_PRECUNEUS', 'CTX_LH_SUPERIORPARIETAL', 'CTX_LH_SUPRAMARGINAL', 'CTX_RH_INFERIORPARIETAL', 'CTX_RH_PRECUNEUS', 'CTX_RH_SUPERIORPARIETAL', 'CTX_RH_SUPRAMARGINAL', 'CTX_LH_MIDDLETEMPORAL', 'CTX_LH_SUPERIORTEMPORAL', 'CTX_RH_MIDDLETEMPORAL', 'CTX_RH_SUPERIORTEMPORAL', 'CTX_LH_CAUDALANTERIORCINGULATE', 'CTX_LH_ISTHMUSCINGULATE', 'CTX_LH_POSTERIORCINGULATE', 'CTX_LH_ROSTRALANTERIORCINGULATE', 'CTX_RH_CAUDALANTERIORCINGULATE', 'CTX_RH_ISTHMUSCINGULATE', 'CTX_RH_POSTERIORCINGULATE', 'CTX_RH_ROSTRALANTERIORCINGULATE')

for (region in regions) {
  df[region] = df[region]/df['COMPOSITE_REF']
}
df = df[,c(demog,regions)]

# create factors
df$RID = factor(df$RID)
df$Gender = factor(df$Gender)
df$APOE4_BIN = factor(df$APOE4_BIN)

# Run anova
results = data.frame()
for (region in regions) {
  form = paste(region,'~ accum + Gender + APOE4_BIN + Age.AV45')
  fm = lm(form,df)
  fm.summary = summary(fm)
  accum_coef = as.data.frame(fm.summary$coefficients['accumTRUE',])
  colnames(accum_coef) = c(region)
  results = rbind(results,t(accum_coef))
}
results = results[order(results$`Pr(>|t|)`),]

# bonferroni correct
results$p.bonferroni = p.adjust(results$`Pr(>|t|)`, method = "bonferroni")
results$p.holm = p.adjust(results$`Pr(>|t|)`, method = "holm")

write.csv(results,file=out.name)
